### PR TITLE
Support CommonJS, reading binary files and reading text with UTF-16 surrogate pairs

### PR DESCRIPTION
**Pull request by schl3ck**
This PR adds support for:

* importing with CommonJS (e.g. NodeJS)
* reading binary files
* reading text with UTF-16 surrogate pairs (e.g. emojis)
* a callback method to report the status of writing the tarball
* returning the raw written tarball data (e.g. to compress it afterwards)

I haven't modified it to write UTF-16 surrogate pairs. Should I add that?

### CODE REVIEW

**Comment by ankitrohatgi** [comment]
Hi, thanks for the contribution, sorry for the late response. 

I see quite a few test failures when I run the tests on your PR (instructions: https://github.com/schl3ck/tarballjs#running-unit-tests). Can you also take a look?

**Comment by schl3ck** [comment]
No problem. I'm late too!

I've fixed the tests. Can you please have another look?

**Comment by schl3ck** [comment]
The first support of UTF-16 surrogate pairs didn't work. It now uses `TextEncoder` and `TextDecoder` to support UTF-8. Browser support should be good enough to allow these to be used.

**Comment by ankitrohatgi** [comment]
This looks good! I can go ahead and merge this now.

**Pull request merged**
